src/edc_visit_schedule/urls.py
from django.urls.conf import path, re_path

from .admin_site import edc_visit_schedule_admin
from .views import HomeView, VisitScheduleView

app_name = "edc_visit_schedule"

urlpatterns = [
    path("admin/", edc_visit_schedule_admin.urls),
    re_path(
        r"visit_schedule/(?P<visit_schedule>[0-9A-Za-z_]+)/"
        "(?P<schedule>^[0-9A-Za-z_]+$)/(?P<visit_code>^[0-9]+$)/",
        VisitScheduleView.as_view(),
        name="visit_schedule_url",
    ),
    re_path(
        r"visit_schedule/(?P<visit_schedule>[0-9A-Za-z_]+)/(?P<schedule>^[0-9A-Za-z_]+$)/",
        VisitScheduleView.as_view(),
        name="visit_schedule_url",
    ),
    re_path(
        r"visit_schedule/(?P<visit_schedule>[0-9A-Za-z_]+)/",
        VisitScheduleView.as_view(),
        name="visit_schedule_url",
    ),
    re_path(
        r"visit_schedule/",
        VisitScheduleView.as_view(),
        name="visit_schedule_url",
    ),
    path(r"", HomeView.as_view(), name="home_url"),
]

src/edc_visit_schedule/models/visit_schedule.py
from decimal import Decimal

from django.db import models
from edc_model import models as edc_models

from ..model_mixins import VisitScheduleMethodsModelMixin


class VisitScheduleManager(models.Manager):
    def get_by_natural_key(self, visit_schedule_name, schedule_name, visit_code):
        return self.get(
            visit_schedule_name=visit_schedule_name,
            schedule_name=schedule_name,
            visit_code=visit_code,
        )


class VisitSchedule(VisitScheduleMethodsModelMixin, edc_models.BaseUuidModel):
    visit_schedule_name = models.CharField(max_length=150)

    schedule_name = models.CharField(max_length=150)

    visit_code = models.CharField(max_length=150)

    visit_name = models.CharField(max_length=150)

    visit_title = models.CharField(max_length=150)

    timepoint = models.DecimalField(null=True, decimal_places=1, max_digits=6)

    active = models.BooleanField(default=False)

    objects = VisitScheduleManager()

    history = edc_models.HistoricalRecords()

    def __str__(self):
        return f"{self.visit_code}.0: {self.visit_title}"

    def natural_key(self):
        return (
            self.visit_schedule_name,
            self.schedule_name,
            self.visit_code,
        )

    def next_by_timepoint(self, timepoint: Decimal):
        for obj in self.objects.filter(timepoint__gt=timepoint):
            return obj
        return None

    class Meta(edc_models.BaseUuidModel.Meta):
        # ordering = ("visit_schedule_name", "schedule_name", "visit_code")
        unique_together = (
            ("visit_schedule_name", "schedule_name", "visit_code"),
            ("visit_schedule_name", "schedule_name", "timepoint"),
        )
        indexes = [
            models.Index(
                fields=[
                    "visit_schedule_name",
                    "schedule_name",
                    "visit_code",
                    "visit_name",
                    "visit_title",
                ]
            ),
            models.Index(fields=["visit_schedule_name", "schedule_name", "timepoint"]),
        ]

src/edc_visit_schedule/views/home_view.py
from django.views.generic.base import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar.view_mixin import NavbarViewMixin


class HomeView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = "edc_visit_schedule/home.html"
    navbar_name = "edc_visit_schedule"
    navbar_selected_item = "visit_schedule"

src/edc_visit_schedule/views/visit_schedule_view.py
from typing import Any

from django.views.generic.base import TemplateView
from edc_dashboard.view_mixins import EdcViewMixin
from edc_navbar.view_mixin import NavbarViewMixin

from ..site_visit_schedules import SiteVisitScheduleError, site_visit_schedules


class VisitScheduleView(EdcViewMixin, NavbarViewMixin, TemplateView):
    template_name = "edc_visit_schedule/visit_schedule.html"
    navbar_name = "edc_visit_schedule"
    navbar_selected_item = "visit_schedule"

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        try:
            selected_visit_schedule = site_visit_schedules.get_visit_schedule(
                visit_schedule_name=self.kwargs.get("visit_schedule")
            )
        except SiteVisitScheduleError:
            selected_visit_schedule = None
        kwargs.update(
            {
                "visit_schedules": site_visit_schedules.registry,
                "selected_visit_schedule": selected_visit_schedule,
            }
        )
        return super().get_context_data(**kwargs)

src/edc_visit_schedule/templates/edc_visit_schedule/home.html
{% extends edc_base_template %}
{% load static %}

{% block main %}

{{ block.super }}

  <div class="col-sm-4">&nbsp;
  </div>

  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">Visit Schedule</div>
      <div class="list-group">
        <a id="home_list_group_home" href="{% url 'administration_url' %}" class="list-group-item"><i class="fas fa-reply fa-1x fa-fw" aria-hidden="true"></i> Home</a>
        <a id="home_list_group_visit_schedule" href="{% url 'edc_visit_schedule:visit_schedule_url' %}" class="list-group-item">Visit schedules</a>
        <a id="home_list_group_subject_schedule_history" href="{% url 'edc_visit_schedule_admin:edc_visit_schedule_subjectschedulehistory_changelist' %}" class="list-group-item">Subject schedule history</a>
        {% if perms.edc_visit_schedule %}
          <a id="home_edc_visit_schedule_admin" href="{% url 'edc_visit_schedule_admin:app_list' 'edc_visit_schedule' %}" class="list-group-item">Admin</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="col-sm-4">&nbsp;
  </div>
{% endblock main %}

src/edc_visit_schedule/templates/edc_visit_schedule/subject_schedule_footer_row.html
{% if history_obj %}
  {% if offschedule_datetime %}
    <div class="panel-footer">
      <span class="text text-success">SUBJECT IS OFF SCHEDULE. You may still review the data collection schedule above.</span> <BR><small>Subject was taken off the <b>{{ visit_schedule.verbose_name }} {{ schedule.verbose_name }}</b> schedule on {{ offschedule_datetime|date:"SHORT_DATE_FORMAT" }}. See <a href="{{ href }}">{{ verbose_name }}</a></small>
    </div>
  {% else %}
    <div class="panel-footer">
      <small>Subject was put on this schedule on {{ onschedule_datetime|date:"SHORT_DATE_FORMAT" }}. To take off this schedule complete <a href="{{ href }}">{{ verbose_name }}</a>.</small>
    </div>
  {% endif %}
{% endif %}

src/edc_visit_schedule/templates/edc_visit_schedule/visit_schedule.html
{% extends edc_base_template %}

{% load static %}

{% block main %}

    <div class="container">
        <div><a href="{% url 'edc_visit_schedule:home_url' %}" role="button" class="btn btn-sm btn-primary pull-right clearfix">
          <i class="fas fa-reply fa-1x fa-fw" aria-hidden="true"></i>
        </a>
        </div>
        <div class="panel-group" id="accordion">
            {% for visit_schedule in visit_schedules.values %}
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h6 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#{{ visit_schedule.name }}">
                                Visit Schedule: {{ visit_schedule.verbose_name }} <i class="fas fa-caret-right"></i>
                            </a>
                        </h6>
                    </div>
                    <div id="{{ visit_schedule.name }}" class="panel-collapse collapse">
                        <div class="panel-group" id="accordion1">
                            {% for schedule in visit_schedule.schedules.values %}
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion1"
                                               href="#{{ visit_schedule.name|slugify }}-{{ schedule.name|slugify }}">
                                                Schedule {{ schedule.title }} <i class="fas fa-caret-right"></i>
                                            </a>
                                        </h6>
                                    </div>
                                    <div id="{{ visit_schedule.name|slugify }}-{{ schedule.name|slugify }}" class="panel-collapse collapse in">
                                        <div class="panel-group" id="accordion2">
                                            {% for visit in schedule.visits.values %}
                                                <div class="panel panel-default">
                                                    <div class="panel-heading">
                                                        <h6 class="panel-title">
                                                            <a data-toggle="collapse" data-parent="#accordion2"
                                                               href="#{{ visit_schedule.name|slugify }}-{{ schedule.name|slugify }}-{{ visit|slugify }}">
                                                                Visit {{ visit.title }} <i class="fas fa-caret-right"></i>
                                                            </a>
                                                        </h6>
                                                    </div>
                                                    <div id="{{ visit_schedule.name|slugify }}-{{ schedule.name|slugify }}-{{ visit|slugify }}" class="panel-collapse collapse">
                                                        <div class="table-responsive">
                                                            <table class="table table-hover">
                                                                <thead></thead>
                                                                <tbody>
                                                                {% for crf in visit.crfs %}
                                                                    <tr>
                                                                        <td>{{ crf.show_order }}</td>
                                                                        <td>{{ crf.verbose_name }}</td>
                                                                        <td>
                                                                            {% if crf.required %}Required{% endif %}
                                                                        </td>
                                                                    </tr>
                                                                {% endfor %}
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}